import React from "react";
import Navbar from "../Navigation/Navbar";
import { Box, Typography, Button, makeStyles } from "@material-ui/core";

const useStyles = makeStyles({
  container: {
    width: "100%",
    height: "100vh",
    padding: "0 300px",
    backgroundColor: "#1a202c",
    display: "flex",
    flexDirection: "column",
    color: "white",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
    marginTop: 30,
    marginBottom: 20,
  },
  img: {
    width: "100%",
    padding: "0 100px",
    marginTop: 20,
  },
});

const Blog = () => {
  const classes = useStyles();

  return (
    <>
      <Navbar />
      <Box className={classes.container}>
        <Box className={classes.header}>
          <Typography variant="h3" className={classes.headerTxt}>
            Page Replacement Algorithms
          </Typography>
        </Box>
        <hr />
        <Box className={classes.description}>
          <ul>
            <li>
              • What is a page? - For non-contiguous memory allocation, the
              Logical address Space is divided into fixed-size blocks, called
              pages.
            </li>
            <li>
              • Logical Address or Virtual Address (represented in bits): An
              address generated by the CPU
            </li>
          </ul>
          <img src="./images/fifo.jpg" alt="FIFO" className={classes.img} />
        </Box>
      </Box>
    </>
  );
};

export default Blog;
